/**
 * PluginMarketDetail — modal detail view for a marketplace entry.
 *
 * Layout (Task 14 / G14): a 5-tab detail page mirroring the structure
 * of a typical plugin marketplace card (npm / VS Code Marketplace):
 *
 *   - Overview      — name, id, version, author, tags, description
 *   - Changelog     — per-version release notes + install/rollback actions
 *                     (this absorbs the previous G5 "history" tab: the
 *                     changelog *is* the per-version history).
 *   - Permissions   — permissions the plugin would request (from the
 *                     installed copy when present; otherwise an empty
 *                     state explaining the index doesn't declare them).
 *   - Dependencies  — peer-plugin dependency resolution (G4) lifted
 *                     out of the overview tab so the deps sub-tree
 *                     gets the room it deserves.
 *   - Reviews       — empty state. The reviews subsystem hasn't been
 *                     built yet, so the tab stays in the chrome as a
 *                     visible "coming soon" affordance.
 *
 * Tab strip is always visible (no conditional rendering on whether
 * tabs have data) so the chrome doesn't pop in/out as the user
 * installs / uninstalls. Empty states live *inside* each tab.
 *
 * Install / update / rollback actions go through `src/lib/plugin-market.ts`
 * (which wraps the Tauri commands). After a successful install we
 * re-trigger the marketplace store's `refreshUpdates` and notify the
 * parent to close. Per-version installs reuse the G1 SHA-256 path
 * (`downloadPluginVersion` caches by per-version digest) and forward
 * the explicit `version` string to the host so the on-disk
 * `.versions/<v>/` directory is created with the right name.
 */
import { useEffect, useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'
import {
  Download,
  X,
  Package,
  Loader2,
  CheckCircle2,
  AlertCircle,
  Info,
  Wand2,
  Shield,
  Network,
  ShieldCheck,
  ShieldOff,
} from 'lucide-react'
import { toast } from 'sonner'
import {
  Dialog,
  DialogContent,
} from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import {
  downloadPluginZip,
  downloadPluginVersion,
  installPluginFromBytes,
  listPluginVersions,
  rollbackPlugin,
} from '@/lib/plugin-market'
import { usePluginMarketStore, usePluginStore } from '@/stores'
import { loadAllPlugins } from '@/lib/plugin-loader'
import { scanPlugins } from '@/lib/tauri'
import {
  resolveDependencies,
  parseDependencyList,
  type DependencyResolution,
  type ResolverIndexEntry,
  type ResolverInstalledPlugin,
} from '@/lib/plugin-dependencies'
import type {
  PluginIndex,
  PluginIndexEntry,
  PluginIndexEntryVersion,
  PluginVersionInfo,
  PluginPermission,
} from '@/types/plugin'
import type { PluginMetadataRust } from '@/lib/tauri'

/**
 * The five tabs of the detail dialog. The order here is the order
 * the tabs render in; the strip is generated by mapping over this
 * tuple so adding / re-ordering is a one-line change.
 */
type DetailTab = 'overview' | 'permissions' | 'dependencies'

/**
 * Reload the plugin registry after a successful install / update /
 * rollback. Centralised so every install path (latest version,
 * historical version, rollback) follows the same post-write dance:
 * scan → loadAllPlugins → setPlugins. Without this shared helper
 * each install branch would carry its own copy and any future
 * change to the reload path (e.g. a new failure reporting hook)
 * would have to be made in three places.
 */
async function reloadAfterInstall(): Promise<void> {
  try {
    const list = await scanPlugins()
    const { plugins: defs, failures } = await loadAllPlugins(list)
    usePluginStore.getState().setPlugins(defs)
    // G2: forward any load failures the rescan surfaced so the
    // banner stays consistent with what's on disk.
    usePluginStore.getState().setLoadFailures(failures)
  } catch (e) {
    console.warn('post-install reload failed', e)
  }
}

function friendlyInstallError(
  e: unknown,
  t: (key: string, opts?: { defaultValue: string }) => string,
): string {
  const raw = e instanceof Error ? e.message : String(e)
  const lower = raw.toLowerCase()
  if (lower.includes('sha256 mismatch')) {
    return t('plugin.market.errorSha256Mismatch', {
      defaultValue: 'SHA-256 不匹配:zip 已被替换或损坏,请联系作者',
    })
  }
  if (lower.startsWith('http ') || lower.includes(' downloading ')) {
    return t('plugin.market.errorDownload', {
      defaultValue: '下载失败:网络异常或文件已被移除',
    })
  }
  if (lower.includes('disallowed scheme')) {
    return t('plugin.market.errorScheme', {
      defaultValue: 'repo.json 中 download_url 协议被拒绝(仅允许 http/https)',
    })
  }
  if (lower.includes('missing required')) {
    return t('plugin.market.errorProtocol', {
      defaultValue: 'repo.json 协议错误:插件元数据字段缺失',
    })
  }
  return raw
}

export function PluginMarketDetail({
  entry,
  index,
  localVersion,
  onClose,
  onInstalled,
}: {
  entry: PluginIndexEntry
  index: PluginIndex
  localVersion: string | null
  onClose: () => void
  /**
   * Called by the dialog right before closing, after a successful
   * install / update / rollback. The parent (`PluginMarketView`)
   * uses the returned `PluginMetadataRust` to open the post-install
   * permission grant dialog — the same affordance the user-upload
   * path in `PluginManagerView` provides. Without this callback the
   * marketplace install would silently skip the permission step and
   * the user would have to discover the per-card "Permissions"
   * button before they could grant the first permission.
   *
   * Only the metadata is forwarded (id, name, etc.) — we don't pass
   * the full `PluginDefinition` because the registry might not have
   * picked the new entry up yet by the time the callback runs.
   */
  onInstalled?: (meta: PluginMetadataRust) => void
}) {
  const { t } = useTranslation()
  const refreshUpdates = usePluginMarketStore((s) => s.refreshUpdates)
  // 市场索引 downloadUrl 为相对路径，需 repoUrl 解析。
  const repoUrl = usePluginMarketStore((s) => s.repoUrl)

  const [activeTab, setActiveTab] = useState<DetailTab>('overview')
  const [isInstalling, setIsInstalling] = useState(false)
  // @ts-ignore — kept for future changelog/rollback UI
  const [versions, setVersions] = useState<PluginVersionInfo[]>([])
  // Tracks which specific version the user is installing from the
  // changelog tab — keyed by the version string so two version rows
  // can be in-flight independently (and the per-row spinner lights
  // up only on the row that was clicked, not the whole tab).
  const [installingVersion, setInstallingVersion] = useState<string | null>(null)
  const [isRolling, setIsRolling] = useState<string | null>(null)
  const [error, setError] = useState<string | null>(null)

  // Load the list of locally-installed versions so the rollback UI
  // is populated before the user clicks anything.
  useEffect(() => {
    let cancelled = false
    void (async () => {
      if (localVersion == null) {
        setVersions([])
        return
      }
      try {
        const v = await listPluginVersions(entry.id)
        if (!cancelled) setVersions(v)
      } catch {
        if (!cancelled) setVersions([])
      }
    })()
    return () => {
      cancelled = true
    }
  }, [entry.id, localVersion])

  // ── Dependency resolution (G4) ─────────────────────────────────────────────
  // The marketplace wire format carries dependencies as a
  // `string[]` of `"<id>@<range>"` entries. We feed the
  // `usePluginStore`'s installed plugins into the resolver so
  // the user sees, in real time, which deps are missing,
  // present-but-wrong, or part of a cycle. The resolver is
  // pure (no I/O), so the `useMemo` is cheap and re-runs only
  // when the index entry, the installed list, or the index
  // map change.
  const installedPluginsMap = usePluginStore((s) => s.plugins)
  const indexMap = useMemo<Record<string, ResolverIndexEntry>>(() => {
    const m: Record<string, ResolverIndexEntry> = {}
    for (const e of index.plugins) m[e.id] = { id: e.id, version: e.version }
    return m
  }, [index])
  const installedMap = useMemo<Record<string, ResolverInstalledPlugin>>(() => {
    const m: Record<string, ResolverInstalledPlugin> = {}
    for (const p of installedPluginsMap) {
      m[p.id] = { version: p.version, dependencies: p.dependencies }
    }
    return m
  }, [installedPluginsMap])
  const dependencyResolution: DependencyResolution = useMemo(
    () =>
      resolveDependencies(
        {
          id: entry.id,
          version: entry.version,
          dependencies: parseDependencyList(entry.dependencies),
        },
        installedMap,
        indexMap,
      ),
    [entry.id, entry.version, entry.dependencies, installedMap, indexMap],
  )
  // 存在未满足版本或循环依赖时禁用安装按钮。
  const hasBlockingDependencyIssue =
    dependencyResolution.unsatisfied.length > 0 ||
    dependencyResolution.cycles.length > 0
  // Whether the auto-resolve button can fire: there's at least
  // one missing dep whose `available` slot is filled by the
  // marketplace index. Missing deps with no index entry are
  // un-installable from the marketplace, so the button is
  // hidden.
  const canAutoResolve = dependencyResolution.missing.some(
    (m) => m.available.length > 0,
  )
  const [isAutoResolving, setIsAutoResolving] = useState(false)

  // The locally-installed plugin copy (if any). Used by the
  // Permissions tab to show the actual declared permissions
  // for this id — the marketplace index itself doesn't carry
  // a permissions list, so without the installed copy we'd
  // always have to render the "unknown" empty state.
  const installedPlugin = usePluginStore((s) =>
    s.plugins.find((p) => p.id === entry.id) ?? null,
  )
  const declaredPermissions: PluginPermission[] = installedPlugin?.permissions ?? []

  /**
   * Install one plugin entry from the marketplace index. Lifted
   * out of `onInstall` so the auto-resolve flow can install
   * missing dependencies without re-implementing the
   * download → install → reload → toast chain. Returns the
   * installed metadata on success, or throws on failure (so
   * callers can short-circuit the chain).
   */
  const installEntry = async (
    e: PluginIndexEntry
  ): Promise<PluginMetadataRust | null> => {
    const bytes = await downloadPluginZip(e, repoUrl)
    return installPluginFromBytes({
      pluginId: e.id,
      version: e.version,
      bytes,
      sha256: e.sha256,
    })
  }

  const onInstall = async () => {
    // 防止双击重复安装。
    if (isInstalling || installingVersion !== null) return
    setError(null)
    // 点击时重新检查依赖。
    if (hasBlockingDependencyIssue) {
      const reason =
        dependencyResolution.cycles.length > 0
          ? t('plugin.market.depsCycleDetected', {
              defaultValue: '检测到循环依赖，无法安装',
            })
          : t('plugin.market.depsUnsatisfied', {
              defaultValue: '依赖版本不满足，无法安装',
            })
      setError(reason)
      return
    }
    setIsInstalling(true)
    let installedMeta: PluginMetadataRust | null = null
    try {
      installedMeta = await installEntry(entry)
      // The host successfully wrote the plugin. Run the full reload
      // path (scan → loadAllPlugins → setPlugins) so the new entry
      // is registered with the store *and* gets its `onLoad` hook
      // fired by the host-takeover layer. A shortcut like
      // `setPlugins(list as any)` would skip `loadAllPlugins` and
      // the onLoad hook would never run, leaving the plugin's
      // event subscriptions / storage seeding silent.
      await reloadAfterInstall()
      await refreshUpdates()
      toast.success(
        t('plugin.market.installed', {
          defaultValue: '已安装 {{name}} v{{version}}',
          name: entry.name,
          version: entry.version,
        })
      )
      // Hand off to the parent so the post-install permission
      // dialog can open with the freshly-loaded plugin's declared
      // permission list. The parent closes this dialog and opens
      // the permission modal in a follow-up tick so the two
      // dialogs don't stack.
      if (onInstalled && installedMeta) {
        onInstalled(installedMeta)
      } else {
        onClose()
      }
    } catch (e: any) {
      setError(friendlyInstallError(e, t))
    } finally {
      setIsInstalling(false)
    }
  }

  /**
   * Auto-resolve missing dependencies by installing each one
   * that's available in the marketplace index. The flow is
   * deliberately simple: one pass through the *immediate*
   * missing list. Transitive dependencies (a missing dep
   * whose own deps are also missing) require a second click
   * after the first round of installs lands; surfacing a
   * recursive resolver here would muddle the UX with hidden
   * state and potential permission dialogs. We do bail early
   * on the first failure so a single broken download doesn't
   * hold up the queue.
   *
   * After the chain succeeds we still leave the original
   * "install" decision to the user — auto-resolve only stages
   * the dependencies. The next click of "Install" runs the
   * full pre-install check again, and the resolution banner
   * either vanishes (deps satisfied) or surfaces any
   * remaining issues.
   */
  const onAutoResolve = async () => {
    setError(null)
    if (!canAutoResolve || isAutoResolving) return
    setIsAutoResolving(true)
    let succeeded = 0
    let failed = 0
    try {
      for (const missing of dependencyResolution.missing) {
        if (!missing.available) continue
        const depEntry = index.plugins.find((e) => e.id === missing.id) ?? null
        if (!depEntry) {
          // Marketplace no longer carries this id (race vs
          // index refresh). Skip rather than block.
          failed++
          continue
        }
        try {
          await installEntry(depEntry)
          succeeded++
        } catch {
          failed++
        }
      }
      await reloadAfterInstall()
      await refreshUpdates()
      if (succeeded > 0) {
        toast.success(
          t('plugin.market.depsAutoResolved', {
            defaultValue: '已自动解决 {{count}} 个依赖',
            count: succeeded,
          }),
        )
      }
      if (failed > 0) {
        toast.error(
          t('plugin.market.depsAutoResolveFailed', {
            defaultValue: '{{count}} 个依赖安装失败',
            count: failed,
          }),
        )
      }
    } catch (e: any) {
      setError(friendlyInstallError(e, t))
    } finally {
      setIsAutoResolving(false)
    }
  }

  /**
   * Install a specific historical version (Task 5 / G5). The
   * version comes from the `versions` array on the index entry —
   * the host receives the explicit `version` string so the on-disk
   * `.versions/<v>/` directory is named correctly. The SHA-256 we
   * pass is the per-version digest (G1 reuse), not the latest
   * entry-level digest, and the signature is the entry-level one
   * (the index protocol attaches one signature per `PluginIndexEntry`,
   * not per version).
   */
  // @ts-ignore — kept for future per-version install UI
  const onInstallVersion = async (version: PluginIndexEntryVersion) => {
    // Same early guard as `onInstall`: don't queue a second per-version
    // install while the first one is still in flight, and don't
    // race against a top-level install. `version.version` is the
    // natural idempotency key for the per-version entry point.
    if (isInstalling || installingVersion !== null || isRolling !== null) {
      return
    }
    setError(null)
    setInstallingVersion(version.version)
    let installedMeta: PluginMetadataRust | null = null
    try {
      const bytes = await downloadPluginVersion(entry.id, version, repoUrl)
      installedMeta = await installPluginFromBytes({
        pluginId: entry.id,
        version: version.version,
        bytes,
        sha256: version.sha256,
      })
      await reloadAfterInstall()
      await refreshUpdates()
      toast.success(
        t('plugin.market.installedVersion', {
          defaultValue: '已安装 {{name}} v{{version}}',
          name: entry.name,
          version: version.version,
        })
      )
      if (onInstalled && installedMeta) {
        onInstalled(installedMeta)
      } else {
        onClose()
      }
    } catch (e: any) {
      setError(friendlyInstallError(e, t))
    } finally {
      setInstallingVersion(null)
    }
  }

  // @ts-ignore — kept for future rollback UI
  const onRollback = async (version: string) => {
    // 防止回滚并发。
    if (isInstalling || installingVersion !== null || isRolling !== null) {
      return
    }
    setError(null)
    setIsRolling(version)
    try {
      await rollbackPlugin(entry.id, version)
      // Same full-reload path as install. Rolling back to a previous
      // version is conceptually a fresh plugin load, so we want
      // onLoad/onUnload to fire cleanly.
      await reloadAfterInstall()
      await refreshUpdates()
      toast.success(
        t('plugin.market.rolledBack', {
          defaultValue: '已回滚到 {{version}}',
          version,
        })
      )
      // 回滚不重新弹权限对话框。
      onClose()
    } catch (e: any) {
      setError(friendlyInstallError(e, t))
    } finally {
      setIsRolling(null)
    }
  }

  const isInstalled = localVersion != null
  const isUpdateAvailable = isInstalled && localVersion !== entry.version
  // `entry.versions` is the optional wire-format list (newest first).
  // Fresh publishes omit it (the marketplace only ships the latest
  // artifact), so the array is `undefined` rather than `[]` in that
  // case; we coerce to `[]` here to keep the rest of the render code
  // agnostic to the optionality.

  // Stable count of declared dependencies, used to badge the
  // Dependencies tab in the strip so the user can tell at a
  // glance whether the plugin has any peer-plugin requirements.
  const declaredDepsCount = parseDependencyList(entry.dependencies).length

  return (
    <Dialog open onOpenChange={(o) => !o && onClose()}>
      <DialogContent className="pa-popup" style={{ maxWidth: 560, maxHeight: '80vh', display: 'flex', flexDirection: 'column',gap:0 }}>
        <div className="pmd-header">
          <span className="pmd-header-icon">
            <Package size={18} />
          </span>
          <span className="pmd-header-info">
            <span className="pmd-header-title">
              {entry.name || t('plugin.market.unknownName', { defaultValue: '未命名插件' })}
              <span className="pa-market-badge is-xs">
                v{entry.version}
              </span>
              {isUpdateAvailable && (
                <span className="pa-market-badge is-update is-xs">
                  {t('plugin.market.badgeUpdate', { defaultValue: 'Update' })}
                </span>
              )}
              {isInstalled && !isUpdateAvailable && (
                <span className="pa-market-badge is-installed is-xs">
                  {t('plugin.market.badgeInstalled', { defaultValue: 'Installed' })}
                </span>
              )}
            </span>
            <span className="pmd-header-id">
              {entry.id}
            </span>
          </span>
        </div>

        {/*
          Tab strip. Always visible so the chrome doesn't pop in/out
          as the user installs / uninstalls the plugin (which can
          change `localVersion` mid-session). Each tab carries an
          icon + label and the active state is a 2px accent border
          (mirroring common settings / marketplace tab strips). The
          count badges (deps / permissions) hint at content without
          forcing the user to switch tabs to find out.
        */}
        <div
          role="tablist"
          className="pmd-tabstrip"
        >
          <DetailTabButton
            label={t('plugin.market.tabOverview', { defaultValue: '基本信息' })}
            icon={<Info size={12} />}
            active={activeTab === 'overview'}
            onClick={() => setActiveTab('overview')}
            data-testid="pmd-tab-overview"
          />
          <DetailTabButton
            label={t('plugin.market.tabPermissions', { defaultValue: '权限' })}
            icon={<Shield size={12} />}
            active={activeTab === 'permissions'}
            onClick={() => setActiveTab('permissions')}
            badge={isInstalled ? declaredPermissions.length : undefined}
            data-testid="pmd-tab-permissions"
          />
          <DetailTabButton
            label={t('plugin.market.tabDependencies', { defaultValue: '依赖' })}
            icon={<Network size={12} />}
            active={activeTab === 'dependencies'}
            onClick={() => setActiveTab('dependencies')}
            badge={declaredDepsCount > 0 ? declaredDepsCount : undefined}
            data-testid="pmd-tab-dependencies"
          />
        </div>

        <div className="pmd-body">
          <div className="pmd-tabpanel">
            {/*
              "基本信息" tab — name + id + author + tags + description.
              The dependency summary that used to live here has been
              moved to its own tab (Task 14 / G14). Nothing else
              semantically changed beyond the tab switcher above.
            */}
            {activeTab === 'overview' && (
              <div className="pmd-overview">
                <OverviewPanel
                  entry={entry}
                  localVersion={localVersion}
                  isInstalled={isInstalled}
                  isUpdateAvailable={isUpdateAvailable}
                />
              </div>
            )}

            {/*
              权限 Tab。
            */}
            {activeTab === 'permissions' && (
              <div className="pmd-permissions">
                <PermissionsPanel
                  isInstalled={isInstalled}
                  declaredPermissions={declaredPermissions}
                />
              </div>
            )}

            {/*
              "依赖" tab (G4) — full dependency resolution list,
              lifted out of the previous overview sub-section. The
              per-row icon + label communicates the same verdict
              (✓ satisfied, ⚠ version mismatch, ✗ missing, ⛔
              cycle) but in a dedicated panel.
            */}
            {activeTab === 'dependencies' && (
              <div className="pmd-dependencies">
                <DependenciesPanel
                  entry={entry}
                  dependencyResolution={dependencyResolution}
                  hasBlockingDependencyIssue={hasBlockingDependencyIssue}
                />
              </div>
            )}

            {error && (
              <div className="pmd-error">
                <AlertCircle size={14} style={{ flexShrink: 0, marginTop: 1 }} />
                <span>{error}</span>
              </div>
            )}
          </div>
        </div>

        <div className="pmd-footer">
          <Button variant="outline" onClick={onClose} disabled={isInstalling || installingVersion !== null || isRolling !== null || isAutoResolving}>
            <X size={14} />
            {t('common.close', { defaultValue: '关闭' })}
          </Button>
          {/* "自动解决依赖" affordance. Only shown when there's
              at least one missing dep that's also present in
              the marketplace index (i.e. we know how to
              install it). The button runs a sequential
              install for each missing dep; the user clicks
              "Install" again afterwards to retry the parent
              plugin. */}
          {canAutoResolve && (
            <Button
              variant="outline"
              onClick={onAutoResolve}
              disabled={isAutoResolving || isInstalling}
              data-testid="plugin-auto-resolve"
            >
              {isAutoResolving ? (
                <Loader2 size={14} className="animate-spin" />
              ) : (
                <Wand2 size={14} />
              )}
              {t('plugin.market.autoResolve', {
                defaultValue: '自动解决依赖',
              })}
            </Button>
          )}
          {!isInstalled && (
            <Button
              onClick={onInstall}
              disabled={isInstalling || installingVersion !== null || hasBlockingDependencyIssue}
              data-testid="plugin-install"
            >
              {isInstalling ? <Loader2 size={14} className="animate-spin" /> : <Download size={14} />}
              {t('plugin.market.install', { defaultValue: '安装' })}
            </Button>
          )}
          {isUpdateAvailable && (
            <Button
              onClick={onInstall}
              disabled={isInstalling || installingVersion !== null || hasBlockingDependencyIssue}
            >
              {isInstalling ? <Loader2 size={14} className="animate-spin" /> : <Download size={14} />}
              {t('plugin.market.updateTo', {
                defaultValue: '更新到 v{{version}}',
                version: entry.version,
              })}
            </Button>
          )}

        </div>
      </DialogContent>
    </Dialog>
  )
}

/**
 * Inline-styled tab button so the chrome matches the rest of the
 * detail dialog (which uses inline `var(--*)` styles). Active
 * state is a 2px bottom border in the accent colour, mirroring
 * common marketplace / settings tab strips.
 *
 * The icon + label sit on a single flex row, vertically centred,
 * so the strip stays compact on narrow viewports (icons are
 * always aligned regardless of label width). An optional
 * `badge` renders a small count chip to the right of the label
 * (used for the Permissions / Dependencies tabs).
 */
function DetailTabButton({
  label,
  icon,
  active,
  onClick,
  badge,
  'data-testid': dataTestId,
}: {
  label: string
  icon: React.ReactNode
  active: boolean
  onClick: () => void
  badge?: number
  'data-testid'?: string
}) {
  return (
    <button
      type="button"
      role="tab"
      aria-selected={active}
      onClick={onClick}
      data-testid={dataTestId}
      className={`pmd-tab${active ? ' is-active' : ''}`}
    >
      {icon}
      <span>{label}</span>
      {typeof badge === 'number' && badge > 0 && (
        <span className="pmd-tab-badge">{badge}</span>
      )}
    </button>
  )
}

/**
 * `YYYY-MM-DD` for an ISO-8601 timestamp. Falls back to the input
 * string if parsing fails so a malformed `publishedAt` never
 * crashes the row. (Mirrors `formatDate` in `PluginMarketView` —
 * kept duplicated here so the detail dialog stays a self-contained
 * component without a cross-component helper import.)
 */
// @ts-ignore — kept for future use in the detail dialog.
function formatDate(dateStr: string): string {
  if (!dateStr) return ''
  try {
    const d = new Date(dateStr)
    if (Number.isNaN(d.getTime())) return dateStr
    const y = d.getFullYear()
    const m = String(d.getMonth() + 1).padStart(2, '0')
    const day = String(d.getDate()).padStart(2, '0')
    return `${y}-${m}-${day}`
  } catch {
    return dateStr
  }
}

/**
 * "基本信息" tab — name + id + author + tags + description.
 *
 * Extracted out of the main `PluginMarketDetail` body so the
 * dialog render path stays focused on flow control. Visual style
 * is the same as the previous overview section; only the
 * dependency sub-tree has been moved to its own tab.
 */

/** 通用居中空状态组件。 */
function EmptyStatePanel({
  icon,
  title,
  hint,
}: {
  icon: React.ReactNode
  title: string
  hint?: string
}) {
  return (
    <div
      data-testid="pmd-empty"
      className="pmd-empty"
    >
      <span className="pmd-empty-icon">
        {icon}
      </span>
      <div className="pmd-empty-title">{title}</div>
      {hint && <div className="pmd-empty-hint">{hint}</div>}
    </div>
  )
}

function OverviewPanel({
  entry,
  localVersion,
  isInstalled,
  isUpdateAvailable,
}: {
  entry: PluginIndexEntry
  localVersion: string | null
  isInstalled: boolean
  isUpdateAvailable: boolean
}) {
  const { t } = useTranslation()
  const dateText = entry.publishedAt
    ? new Date(entry.publishedAt).toISOString().slice(0, 10)
    : null

  return (
    <div className="pmd-overview">
      {/* 描述 */}
      <p className="pmd-desc">
        {entry.description || t('plugin.market.noDescription', { defaultValue: '暂无描述' })}
      </p>

      {/* 元信息行 */}
      <div className="pmd-meta-line">
        <span className="pmd-meta-dot">v{entry.version}</span>
        <span className="pmd-meta-sep">·</span>
        <span className="pmd-meta-dot">{entry.author || t('plugin.market.unknownAuthor', { defaultValue: '未知作者' })}</span>
        {dateText && (
          <>
            <span className="pmd-meta-sep">·</span>
            <span className="pmd-meta-dot">{dateText}</span>
          </>
        )}
        <span className="pmd-meta-sep">·</span>
        {isInstalled ? (
          isUpdateAvailable ? (
            <>
              <span className="pa-market-badge is-update is-xs">
                {t('plugin.market.badgeUpdate', { defaultValue: 'UPDATE' })}
              </span>
              {localVersion && (
                <span className="pmd-meta-dot is-warn">
                  {t('plugin.market.local', { defaultValue: '本地' })} v{localVersion}
                </span>
              )}
            </>
          ) : (
            <span className="pa-market-badge is-installed is-xs">
              {t('plugin.market.badgeInstalled', { defaultValue: 'INSTALLED' })}
            </span>
          )
        ) : (
          <span className="pa-market-badge is-install is-xs">
            {t('plugin.market.badgeInstall', { defaultValue: 'INSTALL' })}
          </span>
        )}
      </div>

      {/* 标签 */}
      {entry.tags.length > 0 && (
        <div className="pmd-tags-row">
          {entry.tags.map((tag) => (
            <span key={tag} className="pa-market-badge">{tag}</span>
          ))}
        </div>
      )}
    </div>
  )
}

/**
 * "权限" tab — permissions the installed copy of the plugin
 * declared in its manifest. The marketplace index doesn't carry
 * a permission list, so for not-yet-installed plugins we render
 * a centred empty state explaining why. The list rows map a
 * `PluginPermission` to the matching `PLUGIN_PERMISSIONS` entry
 * (for the human-readable name + description) and colour-code
 * the granted / pending state.
 */
function PermissionsPanel({
  isInstalled,
  declaredPermissions,
}: {
  isInstalled: boolean
  declaredPermissions: PluginPermission[]
}) {
  const { t } = useTranslation()

  if (!isInstalled) {
    return (
      <EmptyStatePanel
        icon={<Shield size={28} />}
        title={t('plugin.market.permissionsEmpty', {
          defaultValue: '市场清单未声明该插件的权限项。',
        })}
        hint={t('plugin.market.permissionsEmptyHint', {
          defaultValue: '安装后将展示实际请求的权限。',
        })}
      />
    )
  }

  if (declaredPermissions.length === 0) {
    return (
      <EmptyStatePanel
        icon={<ShieldOff size={28} />}
        title={t('plugin.market.permissionsEmpty', {
          defaultValue: '市场清单未声明该插件的权限项。',
        })}
        hint={t('plugin.market.permissionsEmptyHint', {
          defaultValue: '安装后将展示实际请求的权限。',
        })}
      />
    )
  }

  return (
    <ul
      data-testid="pmd-permissions-list"
      className="pmd-permissions"
    >
      {declaredPermissions.map((perm) => {
        return (
          <li
            key={perm}
            data-testid="pmd-permission-row"
            className="pmd-perm-row"
          >
            <span className="pmd-perm-icon">
              <ShieldCheck size={14} />
            </span>
            <div className="pmd-perm-info">
              <div className="pmd-perm-name">
                <span>{t(`plugin.permission.items.${perm}.name`)}</span>
                <span className="pa-market-badge is-installed is-xs">
                  {t('plugin.market.permissionsRequested', { defaultValue: '已请求' })}
                </span>
              </div>
              <div className="pmd-perm-desc">
                {t(`plugin.permission.items.${perm}.description`)}
              </div>
            </div>
          </li>
        )
      })}
    </ul>
  )
}

/** 依赖 Tab（G4）。 */
function DependenciesPanel({
  entry,
  dependencyResolution,
  hasBlockingDependencyIssue,
}: {
  entry: PluginIndexEntry
  dependencyResolution: DependencyResolution
  hasBlockingDependencyIssue: boolean
}) {
  const { t } = useTranslation()
  const declaredDeps = parseDependencyList(entry.dependencies)
  if (declaredDeps.length === 0) {
    return (
      <EmptyStatePanel
        icon={<Network size={28} />}
        title={t('plugin.market.dependenciesEmpty', {
          defaultValue: '该插件没有声明任何依赖。',
        })}
      />
    )
  }
  return (
    <>
      <DependencyResolutionList resolution={dependencyResolution} />
      {hasBlockingDependencyIssue && (
        <div role="alert" className="pmd-deps-alert">
          <AlertCircle size={14} style={{ flexShrink: 0, marginTop: 1 }} />
          <span>
            {dependencyResolution.cycles.length > 0
              ? t('plugin.market.depsCycleDetected', {
                  defaultValue: '检测到循环依赖，无法安装',
                })
              : t('plugin.market.depsUnsatisfied', {
                  defaultValue: '依赖版本不满足，无法安装',
                })}
          </span>
        </div>
      )}
    </>
  )
}

/**
 * 依赖状态列表，每行四种状态之一：satisfied/missing/unsatisfied/cycle。
 */
function DependencyResolutionList({
  resolution,
}: {
  resolution: DependencyResolution
}) {
  const { t } = useTranslation()
  const { root } = resolution
  // Build a quick lookup so we can decorate each declared
  // dep with its resolved status. Unsatisfied / missing /
  // cycle / satisfied each have distinct entries.
  const missingById = new Map(resolution.missing.map((m) => [m.id, m]))
  const unsatisfiedById = new Map(
    resolution.unsatisfied.map((u) => [u.id, u]),
  )
  const cycleIds = new Set<string>()
  for (const c of resolution.cycles) {
    for (const id of c.path) cycleIds.add(id)
  }

  return (
    <ul
      data-testid="plugin-deps-list"
      className="pmd-deps"
    >
      {root.dependencies.map((dep) => {
        const inCycle = cycleIds.has(dep.id)
        const unsatisfied = unsatisfiedById.get(dep.id)
        const missing = missingById.get(dep.id)
        const status = inCycle
          ? {
              cls: 'is-cycle',
              icon: <AlertCircle size={12} />,
              label: t('plugin.market.depsStatusCycle', {
                defaultValue: '循环依赖',
              }),
            }
          : unsatisfied
          ? {
              cls: 'is-unsatisfied',
              icon: <AlertCircle size={12} />,
              label:
                unsatisfied.kind === 'invalid-range'
                  ? t('plugin.market.depsStatusInvalidRange', {
                      defaultValue: '清单中的依赖范围无效',
                    })
                  : unsatisfied.kind === 'unparseable-version'
                  ? t('plugin.market.depsStatusUnparseable', {
                      defaultValue: '已安装版本无法解析',
                    })
                  : t('plugin.market.depsStatusUnsatisfied', {
                      defaultValue: `本地 v${unsatisfied.installed}，需要 ${unsatisfied.required}`,
                    }),
            }
          : missing
          ? {
              cls: 'is-missing',
              icon: <AlertCircle size={12} />,
              label: missing.available
                ? t('plugin.market.depsStatusMissingWithAvailable', {
                    defaultValue: `仓库提供 v${missing.available}`,
                  })
                : t('plugin.market.depsStatusMissingNoSource', {
                    defaultValue: '未找到来源',
                  }),
            }
          : {
              cls: 'is-ok',
              icon: <CheckCircle2 size={12} />,
              label: t('plugin.market.depsStatusSatisfied', {
                defaultValue: '已满足',
              }),
            }
        return (
          <li
            key={dep.id}
            data-testid="plugin-dep-row"
            data-status={status.cls}
            className="pmd-dep-row"
          >
            <span className={`pmd-dep-status ${status.cls}`}>
              {status.icon}
            </span>
            <span className="pmd-dep-id">{dep.id}</span>
            <span className="pmd-dep-label">{status.label}</span>
          </li>
        )
      })}
    </ul>
  )
}
