/**
 * PluginMarketDetail — modal detail view for a marketplace entry.
 *
 * Layout (Task 14 / G14): a 5-tab detail page mirroring the structure
 * of a typical plugin marketplace card (npm / VS Code Marketplace):
 *
 *   - Overview      — name, id, version, author, tags, description
 *   - Changelog     — per-version release notes + install/rollback actions
 *                     (this absorbs the previous G5 "history" tab: the
 *                     changelog *is* the per-version history).
 *   - Permissions   — permissions the plugin would request (from the
 *                     installed copy when present; otherwise an empty
 *                     state explaining the index doesn't declare them).
 *   - Dependencies  — peer-plugin dependency resolution (G4) lifted
 *                     out of the overview tab so the deps sub-tree
 *                     gets the room it deserves.
 *   - Reviews       — empty state. The reviews subsystem hasn't been
 *                     built yet, so the tab stays in the chrome as a
 *                     visible "coming soon" affordance.
 *
 * Tab strip is always visible (no conditional rendering on whether
 * tabs have data) so the chrome doesn't pop in/out as the user
 * installs / uninstalls. Empty states live *inside* each tab.
 *
 * Install / update / rollback actions go through `src/lib/plugin-market.ts`
 * (which wraps the Tauri commands). After a successful install we
 * re-trigger the marketplace store's `refreshUpdates` and notify the
 * parent to close. Per-version installs reuse the G1 SHA-256 path
 * (`downloadPluginVersion` caches by per-version digest) and forward
 * the explicit `version` string to the host so the on-disk
 * `.versions/<v>/` directory is created with the right name.
 */
import { useEffect, useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'
import {
  Download,
  RotateCcw,
  X,
  Package,
  User,
  Tag,
  History,
  Loader2,
  CheckCircle2,
  AlertCircle,
  Info,
  Hash,
  Calendar,
  Wand2,
  Shield,
  FileText,
  Star,
  Network,
  ShieldCheck,
  ShieldOff,
} from 'lucide-react'
import { toast } from 'sonner'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { ScrollArea } from '@/components/ui/scroll-area'
import {
  downloadPluginZip,
  downloadPluginVersion,
  installPluginFromBytes,
  effectivePubkey,
  listPluginVersions,
  rollbackPlugin,
} from '@/lib/plugin-market'
import { usePluginMarketStore, usePluginStore } from '@/stores'
import { loadAllPlugins } from '@/lib/plugin-loader'
import { scanPlugins } from '@/lib/tauri'
import {
  resolveDependencies,
  parseDependencyList,
  type DependencyResolution,
  type ResolverIndexEntry,
  type ResolverInstalledPlugin,
} from '@/lib/plugin-dependencies'
import type {
  PluginIndex,
  PluginIndexEntry,
  PluginIndexEntryVersion,
  PluginVersionInfo,
  PluginPermission,
} from '@/types/plugin'
import { PLUGIN_PERMISSIONS } from '@/types/plugin'
import type { PluginMetadataRust } from '@/lib/tauri'

/**
 * The five tabs of the detail dialog. The order here is the order
 * the tabs render in; the strip is generated by mapping over this
 * tuple so adding / re-ordering is a one-line change.
 */
type DetailTab = 'overview' | 'changelog' | 'permissions' | 'dependencies' | 'reviews'

/**
 * Reload the plugin registry after a successful install / update /
 * rollback. Centralised so every install path (latest version,
 * historical version, rollback) follows the same post-write dance:
 * scan → loadAllPlugins → setPlugins. Without this shared helper
 * each install branch would carry its own copy and any future
 * change to the reload path (e.g. a new failure reporting hook)
 * would have to be made in three places.
 */
async function reloadAfterInstall(): Promise<void> {
  try {
    const list = await scanPlugins()
    const { plugins: defs, failures } = await loadAllPlugins(list)
    usePluginStore.getState().setPlugins(defs)
    // G2: forward any load failures the rescan surfaced so the
    // banner stays consistent with what's on disk.
    usePluginStore.getState().setLoadFailures(failures)
  } catch (e) {
    console.warn('post-install reload failed', e)
  }
}

export function PluginMarketDetail({
  entry,
  index,
  localVersion,
  onClose,
  onInstalled,
}: {
  entry: PluginIndexEntry
  index: PluginIndex
  localVersion: string | null
  onClose: () => void
  /**
   * Called by the dialog right before closing, after a successful
   * install / update / rollback. The parent (`PluginMarketView`)
   * uses the returned `PluginMetadataRust` to open the post-install
   * permission grant dialog — the same affordance the user-upload
   * path in `PluginManagerView` provides. Without this callback the
   * marketplace install would silently skip the permission step and
   * the user would have to discover the per-card "Permissions"
   * button before they could grant the first permission.
   *
   * Only the metadata is forwarded (id, name, etc.) — we don't pass
   * the full `PluginDefinition` because the registry might not have
   * picked the new entry up yet by the time the callback runs.
   */
  onInstalled?: (meta: PluginMetadataRust) => void
}) {
  const { t } = useTranslation()
  const refreshUpdates = usePluginMarketStore((s) => s.refreshUpdates)

  const [activeTab, setActiveTab] = useState<DetailTab>('overview')
  const [versions, setVersions] = useState<PluginVersionInfo[]>([])
  const [isInstalling, setIsInstalling] = useState(false)
  // Tracks which specific version the user is installing from the
  // changelog tab — keyed by the version string so two version rows
  // can be in-flight independently (and the per-row spinner lights
  // up only on the row that was clicked, not the whole tab).
  const [installingVersion, setInstallingVersion] = useState<string | null>(null)
  const [isRolling, setIsRolling] = useState<string | null>(null)
  const [error, setError] = useState<string | null>(null)

  // Load the list of locally-installed versions so the rollback UI
  // is populated before the user clicks anything.
  useEffect(() => {
    let cancelled = false
    void (async () => {
      if (localVersion == null) {
        setVersions([])
        return
      }
      try {
        const v = await listPluginVersions(entry.id)
        if (!cancelled) setVersions(v)
      } catch {
        if (!cancelled) setVersions([])
      }
    })()
    return () => {
      cancelled = true
    }
  }, [entry.id, localVersion])

  // ── Dependency resolution (G4) ─────────────────────────────────────────────
  // The marketplace wire format carries dependencies as a
  // `string[]` of `"<id>@<range>"` entries. We feed the
  // `usePluginStore`'s installed plugins into the resolver so
  // the user sees, in real time, which deps are missing,
  // present-but-wrong, or part of a cycle. The resolver is
  // pure (no I/O), so the `useMemo` is cheap and re-runs only
  // when the index entry, the installed list, or the index
  // map change.
  const installedPluginsMap = usePluginStore((s) => s.plugins)
  const indexMap = useMemo<Record<string, ResolverIndexEntry>>(() => {
    const m: Record<string, ResolverIndexEntry> = {}
    for (const e of index.plugins) m[e.id] = { id: e.id, version: e.version }
    return m
  }, [index])
  const installedMap = useMemo<Record<string, ResolverInstalledPlugin>>(() => {
    const m: Record<string, ResolverInstalledPlugin> = {}
    for (const p of installedPluginsMap) {
      m[p.id] = { version: p.version, dependencies: p.dependencies }
    }
    return m
  }, [installedPluginsMap])
  const dependencyResolution: DependencyResolution = useMemo(
    () =>
      resolveDependencies(
        {
          id: entry.id,
          version: entry.version,
          dependencies: parseDependencyList(entry.dependencies),
        },
        installedMap,
        indexMap,
      ),
    [entry.id, entry.version, entry.dependencies, installedMap, indexMap],
  )
  // True when the install / update button must be disabled:
  // there are unsatisfied versions (can't be auto-fixed) or
  // detected cycles. Missing deps *do* still let the install
  // proceed if the user resolves them via the auto-resolve
  // button — so the button is only disabled for *hard*
  // failures.
  const hasBlockingDependencyIssue =
    dependencyResolution.unsatisfied.length > 0 ||
    dependencyResolution.cycles.length > 0
  // Whether the auto-resolve button can fire: there's at least
  // one missing dep whose `available` slot is filled by the
  // marketplace index. Missing deps with no index entry are
  // un-installable from the marketplace, so the button is
  // hidden.
  const canAutoResolve = dependencyResolution.missing.some(
    (m) => m.available.length > 0,
  )
  const [isAutoResolving, setIsAutoResolving] = useState(false)

  // The locally-installed plugin copy (if any). Used by the
  // Permissions tab to show the actual declared permissions
  // for this id — the marketplace index itself doesn't carry
  // a permissions list, so without the installed copy we'd
  // always have to render the "unknown" empty state.
  const installedPlugin = usePluginStore((s) =>
    s.plugins.find((p) => p.id === entry.id) ?? null,
  )
  const declaredPermissions: PluginPermission[] = installedPlugin?.permissions ?? []

  /**
   * Install one plugin entry from the marketplace index. Lifted
   * out of `onInstall` so the auto-resolve flow can install
   * missing dependencies without re-implementing the
   * download → install → reload → toast chain. Returns the
   * installed metadata on success, or throws on failure (so
   * callers can short-circuit the chain).
   */
  const installEntry = async (
    e: PluginIndexEntry
  ): Promise<PluginMetadataRust | null> => {
    const bytes = await downloadPluginZip(e)
    const pubkeyB64 = effectivePubkey(index, e)
    return installPluginFromBytes({
      pluginId: e.id,
      version: e.version,
      bytes,
      sha256: e.sha256,
      pubkeyB64,
      signatureB64: e.signatureB64,
    })
  }

  const onInstall = async () => {
    // Early guard against double-clicks landing in the same render
    // cycle. The button's `disabled` prop already covers the slow
    // case (state has flipped to `isInstalling` by the time React
    // re-renders) but a synchronous double-click before any state
    // update commits would otherwise queue two installs and
    // produce two success toasts for the same plugin.
    if (isInstalling || installingVersion !== null) return
    setError(null)
    // Re-check at click time: the user might have updated the
    // store via the install manager tab between the resolution
    // memo and this click. If something is still off (hard
    // failures only — missing deps the user hasn't yet
    // resolved), refuse and surface the same banner the dialog
    // already shows.
    if (hasBlockingDependencyIssue) {
      const reason =
        dependencyResolution.cycles.length > 0
          ? t('plugin.market.depsCycleDetected', {
              defaultValue: '检测到循环依赖，无法安装',
            })
          : t('plugin.market.depsUnsatisfied', {
              defaultValue: '依赖版本不满足，无法安装',
            })
      setError(reason)
      return
    }
    setIsInstalling(true)
    let installedMeta: PluginMetadataRust | null = null
    try {
      installedMeta = await installEntry(entry)
      // The host successfully wrote the plugin. Run the full reload
      // path (scan → loadAllPlugins → setPlugins) so the new entry
      // is registered with the store *and* gets its `onLoad` hook
      // fired by the host-takeover layer. A shortcut like
      // `setPlugins(list as any)` would skip `loadAllPlugins` and
      // the onLoad hook would never run, leaving the plugin's
      // event subscriptions / storage seeding silent.
      await reloadAfterInstall()
      await refreshUpdates()
      toast.success(
        t('plugin.market.installed', {
          defaultValue: '已安装 {{name}} v{{version}}',
          name: entry.name,
          version: entry.version,
        })
      )
      // Hand off to the parent so the post-install permission
      // dialog can open with the freshly-loaded plugin's declared
      // permission list. The parent closes this dialog and opens
      // the permission modal in a follow-up tick so the two
      // dialogs don't stack.
      if (onInstalled && installedMeta) {
        onInstalled(installedMeta)
      } else {
        onClose()
      }
    } catch (e: any) {
      setError(e?.message ?? String(e))
    } finally {
      setIsInstalling(false)
    }
  }

  /**
   * Auto-resolve missing dependencies by installing each one
   * that's available in the marketplace index. The flow is
   * deliberately simple: one pass through the *immediate*
   * missing list. Transitive dependencies (a missing dep
   * whose own deps are also missing) require a second click
   * after the first round of installs lands; surfacing a
   * recursive resolver here would muddle the UX with hidden
   * state and potential permission dialogs. We do bail early
   * on the first failure so a single broken download doesn't
   * hold up the queue.
   *
   * After the chain succeeds we still leave the original
   * "install" decision to the user — auto-resolve only stages
   * the dependencies. The next click of "Install" runs the
   * full pre-install check again, and the resolution banner
   * either vanishes (deps satisfied) or surfaces any
   * remaining issues.
   */
  const onAutoResolve = async () => {
    setError(null)
    if (!canAutoResolve || isAutoResolving) return
    setIsAutoResolving(true)
    let succeeded = 0
    let failed = 0
    try {
      for (const missing of dependencyResolution.missing) {
        if (!missing.available) continue
        const depEntry = index.plugins.find((e) => e.id === missing.id) ?? null
        if (!depEntry) {
          // Marketplace no longer carries this id (race vs
          // index refresh). Skip rather than block.
          failed++
          continue
        }
        try {
          await installEntry(depEntry)
          succeeded++
        } catch {
          failed++
        }
      }
      await reloadAfterInstall()
      await refreshUpdates()
      if (succeeded > 0) {
        toast.success(
          t('plugin.market.depsAutoResolved', {
            defaultValue: '已自动解决 {{count}} 个依赖',
            count: succeeded,
          }),
        )
      }
      if (failed > 0) {
        toast.error(
          t('plugin.market.depsAutoResolveFailed', {
            defaultValue: '{{count}} 个依赖安装失败',
            count: failed,
          }),
        )
      }
    } catch (e: any) {
      setError(e?.message ?? String(e))
    } finally {
      setIsAutoResolving(false)
    }
  }

  /**
   * Install a specific historical version (Task 5 / G5). The
   * version comes from the `versions` array on the index entry —
   * the host receives the explicit `version` string so the on-disk
   * `.versions/<v>/` directory is named correctly. The SHA-256 we
   * pass is the per-version digest (G1 reuse), not the latest
   * entry-level digest, and the signature is the entry-level one
   * (the index protocol attaches one signature per `PluginIndexEntry`,
   * not per version).
   */
  const onInstallVersion = async (version: PluginIndexEntryVersion) => {
    // Same early guard as `onInstall`: don't queue a second per-version
    // install while the first one is still in flight, and don't
    // race against a top-level install. `version.version` is the
    // natural idempotency key for the per-version entry point.
    if (isInstalling || installingVersion !== null || isRolling !== null) {
      return
    }
    setError(null)
    setInstallingVersion(version.version)
    let installedMeta: PluginMetadataRust | null = null
    try {
      const bytes = await downloadPluginVersion(entry.id, version)
      const pubkeyB64 = effectivePubkey(index, entry)
      installedMeta = await installPluginFromBytes({
        pluginId: entry.id,
        version: version.version,
        bytes,
        sha256: version.sha256,
        pubkeyB64,
        signatureB64: entry.signatureB64,
      })
      await reloadAfterInstall()
      await refreshUpdates()
      toast.success(
        t('plugin.market.installedVersion', {
          defaultValue: '已安装 {{name}} v{{version}}',
          name: entry.name,
          version: version.version,
        })
      )
      if (onInstalled && installedMeta) {
        onInstalled(installedMeta)
      } else {
        onClose()
      }
    } catch (e: any) {
      setError(e?.message ?? String(e))
    } finally {
      setInstallingVersion(null)
    }
  }

  const onRollback = async (version: string) => {
    // Rollback must not race with another install or another
    // rollback. The row's `disabled` prop already covers the slow
    // case; this catches the synchronous double-click window
    // (React hasn't re-rendered yet) and prevents the UI from
    // showing two "Rollback in progress" badges.
    if (isInstalling || installingVersion !== null || isRolling !== null) {
      return
    }
    setError(null)
    setIsRolling(version)
    try {
      await rollbackPlugin(entry.id, version)
      // Same full-reload path as install. Rolling back to a previous
      // version is conceptually a fresh plugin load, so we want
      // onLoad/onUnload to fire cleanly.
      await reloadAfterInstall()
      await refreshUpdates()
      toast.success(
        t('plugin.market.rolledBack', {
          defaultValue: '已回滚到 {{version}}',
          version,
        })
      )
      // A rollback is a re-activation of an already-installed
      // plugin whose permissions were set on the original install.
      // We don't re-open the permission dialog here — the user
      // has already made their decision on the prior install, and
      // re-prompting on every rollback would be a regression.
      // (The post-install path is purely a "first install" affordance.)
      onClose()
    } catch (e: any) {
      setError(e?.message ?? String(e))
    } finally {
      setIsRolling(null)
    }
  }

  const isInstalled = localVersion != null
  const isUpdateAvailable = isInstalled && localVersion !== entry.version
  // `entry.versions` is the wire-format list (newest first). Some
  // older indexes may not ship it; the existing "is at least one
  // version listed" check guards both the tab visibility and the
  // per-row rendering below.
  const hasVersionHistory = entry.versions.length > 0

  // Stable count of declared dependencies, used to badge the
  // Dependencies tab in the strip so the user can tell at a
  // glance whether the plugin has any peer-plugin requirements.
  const declaredDepsCount = parseDependencyList(entry.dependencies).length

  return (
    <Dialog open onOpenChange={(o) => !o && onClose()}>
      <DialogContent style={{ maxWidth: 600, maxHeight: '85vh', display: 'flex', flexDirection: 'column' }}>
        <DialogHeader>
          <DialogTitle style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <Package size={18} />
            {entry.name || t('plugin.market.unknownName', { defaultValue: '未命名插件' })}
            <Badge variant="outline" style={{ marginLeft: 4 }}>
              v{entry.version}
            </Badge>
            {isUpdateAvailable && (
              <Badge style={{ background: 'var(--accent, #4f46e5)', color: 'white' }}>
                <Download size={10} />
                {t('plugin.market.badgeUpdate', { defaultValue: 'Update' })}
              </Badge>
            )}
            {isInstalled && !isUpdateAvailable && (
              <Badge variant="secondary">
                <CheckCircle2 size={10} />
                {t('plugin.market.badgeInstalled', { defaultValue: 'Installed' })}
              </Badge>
            )}
          </DialogTitle>
          <DialogDescription style={{ fontFamily: 'var(--font-mono, monospace)', fontSize: 11 }}>
            {entry.id}
          </DialogDescription>
        </DialogHeader>

        {/*
          Tab strip. Always visible so the chrome doesn't pop in/out
          as the user installs / uninstalls the plugin (which can
          change `localVersion` mid-session). Each tab carries an
          icon + label and the active state is a 2px accent border
          (mirroring common settings / marketplace tab strips). The
          count badges (deps / permissions) hint at content without
          forcing the user to switch tabs to find out.
        */}
        <div
          role="tablist"
          className="pmd-tabstrip"
          style={{
            display: 'flex',
            gap: 0,
            borderBottom: '1px solid var(--border, #e5e5e5)',
            marginBottom: 4,
            flexWrap: 'wrap',
          }}
        >
          <DetailTabButton
            label={t('plugin.market.tabOverview', { defaultValue: '基本信息' })}
            icon={<Info size={12} />}
            active={activeTab === 'overview'}
            onClick={() => setActiveTab('overview')}
            data-testid="pmd-tab-overview"
          />
          <DetailTabButton
            label={t('plugin.market.tabChangelog', { defaultValue: '更新日志' })}
            icon={<FileText size={12} />}
            active={activeTab === 'changelog'}
            onClick={() => setActiveTab('changelog')}
            data-testid="pmd-tab-changelog"
          />
          <DetailTabButton
            label={t('plugin.market.tabPermissions', { defaultValue: '权限' })}
            icon={<Shield size={12} />}
            active={activeTab === 'permissions'}
            onClick={() => setActiveTab('permissions')}
            badge={isInstalled ? declaredPermissions.length : undefined}
            data-testid="pmd-tab-permissions"
          />
          <DetailTabButton
            label={t('plugin.market.tabDependencies', { defaultValue: '依赖' })}
            icon={<Network size={12} />}
            active={activeTab === 'dependencies'}
            onClick={() => setActiveTab('dependencies')}
            badge={declaredDepsCount > 0 ? declaredDepsCount : undefined}
            data-testid="pmd-tab-dependencies"
          />
          <DetailTabButton
            label={t('plugin.market.tabReviews', { defaultValue: '评价' })}
            icon={<Star size={12} />}
            active={activeTab === 'reviews'}
            onClick={() => setActiveTab('reviews')}
            data-testid="pmd-tab-reviews"
          />
        </div>

        <ScrollArea style={{ flex: 1, paddingRight: 8 }}>
          <div
            className="pmd-tabpanel"
            style={{ display: 'flex', flexDirection: 'column', gap: 16, padding: '4px 0' }}
          >
            {/*
              "基本信息" tab — name + id + author + tags + description.
              The dependency summary that used to live here has been
              moved to its own tab (Task 14 / G14). Nothing else
              semantically changed beyond the tab switcher above.
            */}
            {activeTab === 'overview' && (
              <div className="pmd-overview">
                <OverviewPanel
                  entry={entry}
                  localVersion={localVersion}
                  isInstalled={isInstalled}
                  isUpdateAvailable={isUpdateAvailable}
                />
              </div>
            )}

            {/*
              "更新日志" tab (G14 / was G5 "历史版本") — per-version
              release notes (newest first) plus the local versions
              with rollback actions. Lifted out of the old combined
              "overview + history" pair so the changelog text gets
              the room it deserves.
            */}
            {activeTab === 'changelog' && (
              <div className="pmd-changelog">
                <ChangelogPanel
                  entry={entry}
                  hasVersionHistory={hasVersionHistory}
                  versions={versions}
                  isInstalled={isInstalled}
                  localVersion={localVersion}
                  installingVersion={installingVersion}
                  isInstalling={isInstalling}
                  isRolling={isRolling}
                  onInstallVersion={onInstallVersion}
                  onRollback={onRollback}
                />
              </div>
            )}

            {/*
              "权限" tab — shows the permissions the installed copy
              of the plugin declared. The marketplace index doesn't
              ship a permission list (only the on-disk manifest
              does), so for not-yet-installed plugins we render a
              centred empty state explaining why.
            */}
            {activeTab === 'permissions' && (
              <div className="pmd-permissions">
                <PermissionsPanel
                  isInstalled={isInstalled}
                  declaredPermissions={declaredPermissions}
                />
              </div>
            )}

            {/*
              "依赖" tab (G4) — full dependency resolution list,
              lifted out of the previous overview sub-section. The
              per-row icon + label communicates the same verdict
              (✓ satisfied, ⚠ version mismatch, ✗ missing, ⛔
              cycle) but in a dedicated panel.
            */}
            {activeTab === 'dependencies' && (
              <div className="pmd-dependencies">
                <DependenciesPanel
                  entry={entry}
                  dependencyResolution={dependencyResolution}
                  hasBlockingDependencyIssue={hasBlockingDependencyIssue}
                />
              </div>
            )}

            {/*
              "评价" tab — currently a no-content placeholder.
              Reviews aren't a built-in feature of the marketplace
              protocol yet, so we render a centred empty state
              with a "coming soon" hint instead of removing the
              tab from the strip (so the chrome doesn't change
              when the feature lands).
            */}
            {activeTab === 'reviews' && (
              <div className="pmd-reviews">
                <EmptyStatePanel
                  icon={<Star size={28} />}
                  title={t('plugin.market.noReviews', { defaultValue: '暂无评价' })}
                  hint={t('plugin.market.noReviewsHint', {
                    defaultValue: '社区评价系统即将上线。',
                  })}
                />
              </div>
            )}

            {error && (
              <div
                style={{
                  display: 'flex',
                  alignItems: 'flex-start',
                  gap: 6,
                  padding: 8,
                  background: 'rgba(192, 57, 43, 0.08)',
                  border: '1px solid rgba(192, 57, 43, 0.3)',
                  borderRadius: 4,
                  color: 'var(--danger, #c0392b)',
                  fontSize: 12,
                }}
              >
                <AlertCircle size={14} style={{ flexShrink: 0, marginTop: 1 }} />
                <span>{error}</span>
              </div>
            )}
          </div>
        </ScrollArea>

        <DialogFooter style={{ display: 'flex', gap: 8 }}>
          <Button variant="outline" onClick={onClose} disabled={isInstalling || installingVersion !== null || isRolling !== null || isAutoResolving}>
            <X size={14} />
            {t('common.close', { defaultValue: '关闭' })}
          </Button>
          {/* "自动解决依赖" affordance. Only shown when there's
              at least one missing dep that's also present in
              the marketplace index (i.e. we know how to
              install it). The button runs a sequential
              install for each missing dep; the user clicks
              "Install" again afterwards to retry the parent
              plugin. */}
          {canAutoResolve && (
            <Button
              variant="outline"
              onClick={onAutoResolve}
              disabled={isAutoResolving || isInstalling}
              data-testid="plugin-auto-resolve"
            >
              {isAutoResolving ? (
                <Loader2 size={14} className="animate-spin" />
              ) : (
                <Wand2 size={14} />
              )}
              {t('plugin.market.autoResolve', {
                defaultValue: '自动解决依赖',
              })}
            </Button>
          )}
          {!isInstalled && (
            <Button
              onClick={onInstall}
              disabled={isInstalling || installingVersion !== null || hasBlockingDependencyIssue}
              data-testid="plugin-install"
            >
              {isInstalling ? <Loader2 size={14} className="animate-spin" /> : <Download size={14} />}
              {t('plugin.market.install', { defaultValue: '安装' })}
            </Button>
          )}
          {isUpdateAvailable && (
            <Button
              onClick={onInstall}
              disabled={isInstalling || installingVersion !== null || hasBlockingDependencyIssue}
            >
              {isInstalling ? <Loader2 size={14} className="animate-spin" /> : <Download size={14} />}
              {t('plugin.market.updateTo', {
                defaultValue: '更新到 v{{version}}',
                version: entry.version,
              })}
            </Button>
          )}
          {isInstalled && !isUpdateAvailable && (
            <Button variant="outline" disabled>
              <CheckCircle2 size={14} />
              {t('plugin.market.upToDate', { defaultValue: '已是最新' })}
            </Button>
          )}
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}

/**
 * Inline-styled tab button so the chrome matches the rest of the
 * detail dialog (which uses inline `var(--*)` styles). Active
 * state is a 2px bottom border in the accent colour, mirroring
 * common marketplace / settings tab strips.
 *
 * The icon + label sit on a single flex row, vertically centred,
 * so the strip stays compact on narrow viewports (icons are
 * always aligned regardless of label width). An optional
 * `badge` renders a small count chip to the right of the label
 * (used for the Permissions / Dependencies tabs).
 */
function DetailTabButton({
  label,
  icon,
  active,
  onClick,
  badge,
  'data-testid': dataTestId,
}: {
  label: string
  icon: React.ReactNode
  active: boolean
  onClick: () => void
  badge?: number
  'data-testid'?: string
}) {
  return (
    <button
      type="button"
      role="tab"
      aria-selected={active}
      onClick={onClick}
      data-testid={dataTestId}
      className="pmd-tab"
      style={{
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 4,
        padding: '6px 12px',
        fontSize: 12,
        fontWeight: active ? 600 : 400,
        color: active ? 'var(--accent, #4f46e5)' : 'var(--text-secondary)',
        background: 'transparent',
        border: 'none',
        borderBottom: active
          ? '2px solid var(--accent, #4f46e5)'
          : '2px solid transparent',
        cursor: 'pointer',
        transition: 'color 0.15s, border-color 0.15s',
        lineHeight: 1,
        minHeight: 28,
      }}
    >
      <span
        style={{
          display: 'inline-flex',
          alignItems: 'center',
          justifyContent: 'center',
          lineHeight: 0,
        }}
      >
        {icon}
      </span>
      <span>{label}</span>
      {typeof badge === 'number' && badge > 0 && (
        <span
          style={{
            display: 'inline-flex',
            alignItems: 'center',
            justifyContent: 'center',
            minWidth: 16,
            height: 16,
            padding: '0 4px',
            fontSize: 10,
            fontWeight: 600,
            borderRadius: 8,
            background: active ? 'var(--accent, #4f46e5)' : 'var(--border, #e5e5e5)',
            color: active ? 'white' : 'var(--text-secondary)',
          }}
        >
          {badge}
        </span>
      )}
    </button>
  )
}

/**
 * `YYYY-MM-DD` for an ISO-8601 timestamp. Falls back to the input
 * string if parsing fails so a malformed `publishedAt` never
 * crashes the row. (Mirrors `formatDate` in `PluginMarketView` —
 * kept duplicated here so the detail dialog stays a self-contained
 * component without a cross-component helper import.)
 */
function formatDate(dateStr: string): string {
  if (!dateStr) return ''
  try {
    const d = new Date(dateStr)
    if (Number.isNaN(d.getTime())) return dateStr
    const y = d.getFullYear()
    const m = String(d.getMonth() + 1).padStart(2, '0')
    const day = String(d.getDate()).padStart(2, '0')
    return `${y}-${m}-${day}`
  } catch {
    return dateStr
  }
}

/**
 * Generic centred empty-state for tabs that have nothing to show.
 * Used by Reviews (placeholder) and Permissions (when the plugin
 * isn't installed). Lifted to a small component so the three
 * call sites stay visually consistent and a future tweak to the
 * empty-state chrome (icon size, padding, etc.) only needs to be
 * made once.
 */
function EmptyStatePanel({
  icon,
  title,
  hint,
}: {
  icon: React.ReactNode
  title: string
  hint?: string
}) {
  return (
    <div
      data-testid="pmd-empty"
      style={{
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        padding: '32px 16px',
        textAlign: 'center',
        color: 'var(--text-secondary)',
      }}
    >
      <span
        style={{
          display: 'inline-flex',
          alignItems: 'center',
          justifyContent: 'center',
          width: 48,
          height: 48,
          borderRadius: 24,
          background: 'var(--surface-secondary, rgba(0,0,0,0.04))',
          color: 'var(--text-secondary)',
        }}
      >
        {icon}
      </span>
      <div style={{ fontSize: 13, fontWeight: 600, color: 'var(--text-primary, #1f2937)' }}>
        {title}
      </div>
      {hint && <div style={{ fontSize: 12, color: 'var(--text-secondary)' }}>{hint}</div>}
    </div>
  )
}

/**
 * "基本信息" tab — name + id + author + tags + description.
 *
 * Extracted out of the main `PluginMarketDetail` body so the
 * dialog render path stays focused on flow control. Visual style
 * is the same as the previous overview section; only the
 * dependency sub-tree has been moved to its own tab.
 */
function OverviewPanel({
  entry,
  localVersion,
  isInstalled,
  isUpdateAvailable,
}: {
  entry: PluginIndexEntry
  localVersion: string | null
  isInstalled: boolean
  isUpdateAvailable: boolean
}) {
  const { t } = useTranslation()
  return (
    <>
      {/* Author + tags */}
      <div style={{ display: 'flex', gap: 12, alignItems: 'center', flexWrap: 'wrap', fontSize: 12 }}>
        <span style={{ display: 'inline-flex', alignItems: 'center', gap: 4, color: 'var(--text-secondary)' }}>
          <User size={12} />
          {entry.author || t('plugin.market.unknownAuthor', { defaultValue: '未知作者' })}
        </span>
        {entry.tags.length > 0 && (
          <span style={{ display: 'inline-flex', alignItems: 'center', gap: 4, flexWrap: 'wrap' }}>
            <Tag size={12} style={{ color: 'var(--text-secondary)' }} />
            {entry.tags.map((tag) => (
              <Badge key={tag} variant="secondary" style={{ fontSize: 10 }}>
                {tag}
              </Badge>
            ))}
          </span>
        )}
      </div>

      {/* Quick facts: version, install state, local version, published date */}
      <dl
        style={{
          display: 'grid',
          gridTemplateColumns: 'auto 1fr',
          columnGap: 12,
          rowGap: 4,
          margin: 0,
          fontSize: 12,
        }}
      >
        <dt style={{ color: 'var(--text-secondary)' }}>
          {t('plugin.market.overviewVersion', { defaultValue: '版本' })}
        </dt>
        <dd style={{ margin: 0, fontFamily: 'var(--font-mono, monospace)' }}>v{entry.version}</dd>

        <dt style={{ color: 'var(--text-secondary)' }}>
          {t('plugin.market.overviewStatus', { defaultValue: '状态' })}
        </dt>
        <dd style={{ margin: 0, display: 'inline-flex', alignItems: 'center', gap: 4 }}>
          {isInstalled ? (
            isUpdateAvailable ? (
              <>
                <Download size={12} style={{ color: 'var(--accent, #4f46e5)' }} />
                {t('plugin.market.badgeUpdate', { defaultValue: '可更新' })} ·
                <span style={{ color: 'var(--text-secondary)' }}>
                  v{localVersion}
                </span>
              </>
            ) : (
              <>
                <CheckCircle2 size={12} style={{ color: 'var(--success, #16a34a)' }} />
                {t('plugin.market.badgeInstalled', { defaultValue: '已安装' })}
              </>
            )
          ) : (
            <>
              <Info size={12} style={{ color: 'var(--text-secondary)' }} />
              {t('plugin.market.overviewNotInstalled', { defaultValue: '未安装' })}
            </>
          )}
        </dd>
      </dl>

      {/* Description */}
      <section>
        <h4
          style={{
            fontSize: 12,
            fontWeight: 600,
            marginBottom: 4,
            color: 'var(--text-secondary)',
            textTransform: 'uppercase',
            letterSpacing: 0.5,
          }}
        >
          {t('plugin.market.overviewDescription', { defaultValue: '简介' })}
        </h4>
        <p style={{ fontSize: 13, lineHeight: 1.5, margin: 0 }}>
          {entry.description || t('plugin.market.noDescription', { defaultValue: '暂无描述' })}
        </p>
      </section>
    </>
  )
}

/**
 * "更新日志" tab — per-version release notes + install/rollback
 * actions. This is the new home of the G5 version history: the
 * changelog text is the dominant content, with the per-version
 * "install this version" button kept inline so the user can read
 * a release note and act on it without leaving the tab.
 */
function ChangelogPanel({
  entry,
  hasVersionHistory,
  versions,
  isInstalled,
  localVersion,
  installingVersion,
  isInstalling,
  isRolling,
  onInstallVersion,
  onRollback,
}: {
  entry: PluginIndexEntry
  hasVersionHistory: boolean
  versions: PluginVersionInfo[]
  isInstalled: boolean
  localVersion: string | null
  installingVersion: string | null
  isInstalling: boolean
  isRolling: string | null
  onInstallVersion: (v: PluginIndexEntryVersion) => void
  onRollback: (v: string) => void
}) {
  const { t } = useTranslation()

  // Some entries ship `versions` but every row has an empty
  // changelog. Treat that as "no changelog content" so the
  // empty state appears, instead of rendering a list of bare
  // version numbers.
  const hasChangelogContent = entry.versions.some(
    (v) => (v.changelog ?? '').trim().length > 0,
  )

  if (!hasVersionHistory && !(isInstalled && versions.length > 0)) {
    return (
      <EmptyStatePanel
        icon={<FileText size={28} />}
        title={t('plugin.market.noChangelog', {
          defaultValue: '该插件暂未提供更新日志。',
        })}
      />
    )
  }

  return (
    <>
      {/* Per-version changelog (newest first). Each row carries
          the changelog text prominently and a small "install this
          version" affordance in the top-right so the user can
          promote a non-active version without leaving the tab. */}
      {hasVersionHistory && (
        <section>
          <h4
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: 4,
              fontSize: 12,
              fontWeight: 600,
              marginBottom: 6,
              color: 'var(--text-secondary)',
              textTransform: 'uppercase',
              letterSpacing: 0.5,
            }}
          >
            <History size={12} />
            {t('plugin.market.versionHistory', { defaultValue: '版本历史' })}
          </h4>
          {!hasChangelogContent && (
            <p
              style={{
                fontSize: 12,
                color: 'var(--text-secondary)',
                margin: '0 0 6px 0',
              }}
            >
              {t('plugin.market.noChangelog', {
                defaultValue: '该插件暂未提供更新日志。',
              })}
            </p>
          )}
          <ul style={{ listStyle: 'none', margin: 0, padding: 0 }}>
            {entry.versions.map((v) => {
              const isLatest = v.version === entry.version
              const isCurrentLocal = isInstalled && localVersion === v.version
              const isBusy = installingVersion === v.version
              return (
                <li
                  key={v.version}
                  data-testid="plugin-version-row"
                  style={{
                    display: 'flex',
                    flexDirection: 'column',
                    gap: 4,
                    padding: '8px 10px',
                    border: '1px solid var(--border, #e5e5e5)',
                    borderRadius: 4,
                    marginBottom: 6,
                    fontSize: 12,
                  }}
                >
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <span style={{ display: 'inline-flex', alignItems: 'center', gap: 6, fontWeight: 600 }}>
                      v{v.version}
                      {isLatest && (
                        <Badge variant="secondary" style={{ fontSize: 10 }}>
                          {t('plugin.market.latest', { defaultValue: 'latest' })}
                        </Badge>
                      )}
                      {isCurrentLocal && (
                        <Badge variant="secondary" style={{ fontSize: 10 }}>
                          {t('plugin.market.active', { defaultValue: 'active' })}
                        </Badge>
                      )}
                    </span>
                    <Button
                      size="sm"
                      variant="outline"
                      data-testid="plugin-install-version"
                      disabled={isBusy || isInstalling || isRolling !== null}
                      onClick={() => onInstallVersion(v)}
                      title={t('plugin.market.installThisVersion', {
                        defaultValue: '安装此版本',
                      })}
                    >
                      {isBusy ? (
                        <Loader2 size={12} className="animate-spin" />
                      ) : (
                        <Download size={12} />
                      )}
                      {t('plugin.market.installThisVersion', {
                        defaultValue: '安装此版本',
                      })}
                    </Button>
                  </div>
                  <div
                    style={{
                      display: 'flex',
                      alignItems: 'center',
                      gap: 8,
                      color: 'var(--text-secondary)',
                      fontSize: 11,
                    }}
                  >
                    {v.publishedAt && (
                      <span
                        style={{
                          display: 'inline-flex',
                          alignItems: 'center',
                          gap: 4,
                        }}
                      >
                        <Calendar size={10} />
                        {formatDate(v.publishedAt)}
                      </span>
                    )}
                  </div>
                  {v.changelog && (
                    <div
                      style={{
                        color: 'var(--text-primary, #1f2937)',
                        fontSize: 12,
                        lineHeight: 1.5,
                        whiteSpace: 'pre-wrap',
                      }}
                    >
                      {v.changelog}
                    </div>
                  )}
                  {/* Per-version SHA-256 (G1 reuse): the
                      user can compare this with what the
                      host re-hashes on disk. Monospace so
                      long hex strings wrap cleanly. */}
                  {v.sha256 && (
                    <div
                      style={{
                        display: 'inline-flex',
                        alignItems: 'center',
                        gap: 4,
                        color: 'var(--text-secondary)',
                        fontSize: 10,
                        fontFamily: 'var(--font-mono, monospace)',
                        wordBreak: 'break-all',
                      }}
                      title={v.sha256}
                    >
                      <Hash size={10} style={{ flexShrink: 0 }} />
                      <span>{v.sha256}</span>
                    </div>
                  )}
                </li>
              )
            })}
          </ul>
        </section>
      )}

      {/* Local versions + rollback (only when installed) */}
      {isInstalled && versions.length > 0 && (
        <section>
          <h4
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: 4,
              fontSize: 12,
              fontWeight: 600,
              marginBottom: 6,
              color: 'var(--text-secondary)',
              textTransform: 'uppercase',
              letterSpacing: 0.5,
            }}
          >
            <RotateCcw size={12} />
            {t('plugin.market.localVersions', { defaultValue: '已安装版本' })}
          </h4>
          <ul style={{ listStyle: 'none', margin: 0, padding: 0 }}>
            {versions.map((v) => (
              <li
                key={v.version}
                style={{
                  display: 'flex',
                  justifyContent: 'space-between',
                  alignItems: 'center',
                  padding: '6px 8px',
                  border: '1px solid var(--border, #e5e5e5)',
                  borderRadius: 4,
                  marginBottom: 4,
                  fontSize: 12,
                  gap: 8,
                }}
              >
                <span>
                  v{v.version}
                  {v.isActive && (
                    <Badge variant="secondary" style={{ marginLeft: 6, fontSize: 10 }}>
                      {t('plugin.market.active', { defaultValue: 'active' })}
                    </Badge>
                  )}
                </span>
                <Button
                  size="sm"
                  variant="outline"
                  disabled={v.isActive || isRolling === v.version}
                  onClick={() => onRollback(v.version)}
                >
                  {isRolling === v.version ? (
                    <Loader2 size={12} className="animate-spin" />
                  ) : (
                    <RotateCcw size={12} />
                  )}
                  {t('plugin.market.rollback', { defaultValue: '回滚' })}
                </Button>
              </li>
            ))}
          </ul>
        </section>
      )}
    </>
  )
}

/**
 * "权限" tab — permissions the installed copy of the plugin
 * declared in its manifest. The marketplace index doesn't carry
 * a permission list, so for not-yet-installed plugins we render
 * a centred empty state explaining why. The list rows map a
 * `PluginPermission` to the matching `PLUGIN_PERMISSIONS` entry
 * (for the human-readable name + description) and colour-code
 * the granted / pending state.
 */
function PermissionsPanel({
  isInstalled,
  declaredPermissions,
}: {
  isInstalled: boolean
  declaredPermissions: PluginPermission[]
}) {
  const { t } = useTranslation()

  if (!isInstalled) {
    return (
      <EmptyStatePanel
        icon={<Shield size={28} />}
        title={t('plugin.market.permissionsEmpty', {
          defaultValue: '市场清单未声明该插件的权限项。',
        })}
        hint={t('plugin.market.permissionsEmptyHint', {
          defaultValue: '安装后将展示实际请求的权限。',
        })}
      />
    )
  }

  if (declaredPermissions.length === 0) {
    return (
      <EmptyStatePanel
        icon={<ShieldOff size={28} />}
        title={t('plugin.market.permissionsEmpty', {
          defaultValue: '市场清单未声明该插件的权限项。',
        })}
        hint={t('plugin.market.permissionsEmptyHint', {
          defaultValue: '安装后将展示实际请求的权限。',
        })}
      />
    )
  }

  return (
    <ul
      data-testid="pmd-permissions-list"
      style={{
        listStyle: 'none',
        margin: 0,
        padding: 0,
        display: 'flex',
        flexDirection: 'column',
        gap: 6,
      }}
    >
      {declaredPermissions.map((perm) => {
        const info = PLUGIN_PERMISSIONS.find((p) => p.permission === perm)
        return (
          <li
            key={perm}
            data-testid="pmd-permission-row"
            style={{
              display: 'flex',
              alignItems: 'flex-start',
              gap: 8,
              padding: '8px 10px',
              border: '1px solid var(--border, #e5e5e5)',
              borderRadius: 4,
              fontSize: 12,
            }}
          >
            <span
              style={{
                display: 'inline-flex',
                alignItems: 'center',
                justifyContent: 'center',
                flexShrink: 0,
                width: 24,
                height: 24,
                borderRadius: 4,
                background: 'var(--surface-secondary, rgba(0,0,0,0.04))',
                color: 'var(--accent, #4f46e5)',
              }}
            >
              <ShieldCheck size={14} />
            </span>
            <div style={{ flex: 1, minWidth: 0 }}>
              <div
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  gap: 6,
                  fontWeight: 600,
                }}
              >
                <span>{info?.name ?? perm}</span>
                <Badge variant="secondary" style={{ fontSize: 10 }}>
                  {t('plugin.market.permissionsRequested', { defaultValue: '已请求' })}
                </Badge>
              </div>
              <div
                style={{
                  color: 'var(--text-secondary)',
                  fontSize: 11,
                  marginTop: 2,
                  lineHeight: 1.4,
                }}
              >
                {info?.description ?? perm}
              </div>
            </div>
          </li>
        )
      })}
    </ul>
  )
}

/**
 * "依赖" tab — peer-plugin dependency resolution (G4) lifted out
 * of the previous overview sub-section. Shows the resolver's
 * verdict for every declared dep, plus a summary banner when the
 * install would be blocked.
 */
function DependenciesPanel({
  entry,
  dependencyResolution,
  hasBlockingDependencyIssue,
}: {
  entry: PluginIndexEntry
  dependencyResolution: DependencyResolution
  hasBlockingDependencyIssue: boolean
}) {
  const { t } = useTranslation()
  const declaredDeps = parseDependencyList(entry.dependencies)
  if (declaredDeps.length === 0) {
    return (
      <EmptyStatePanel
        icon={<Network size={28} />}
        title={t('plugin.market.dependenciesEmpty', {
          defaultValue: '该插件没有声明任何依赖。',
        })}
      />
    )
  }
  return (
    <>
      <DependencyResolutionList resolution={dependencyResolution} />
      {hasBlockingDependencyIssue && (
        <div
          role="alert"
          style={{
            display: 'flex',
            alignItems: 'flex-start',
            gap: 6,
            marginTop: 6,
            padding: 8,
            background: 'rgba(192, 57, 43, 0.08)',
            border: '1px solid rgba(192, 57, 43, 0.3)',
            borderRadius: 4,
            color: 'var(--danger, #c0392b)',
            fontSize: 12,
          }}
        >
          <AlertCircle size={14} style={{ flexShrink: 0, marginTop: 1 }} />
          <span>
            {dependencyResolution.cycles.length > 0
              ? t('plugin.market.depsCycleDetected', {
                  defaultValue: '检测到循环依赖，无法安装',
                })
              : t('plugin.market.depsUnsatisfied', {
                  defaultValue: '依赖版本不满足，无法安装',
                })}
          </span>
        </div>
      )}
    </>
  )
}

/**
 * Per-dependency status list rendered inside the "依赖"
 * section of `PluginMarketDetail`.
 *
 * Each row in the manifest's `dependencies` array gets one of
 * four states:
 *   - `satisfied`     — installed locally at a version the
 *                       manifest accepts. Green check.
 *   - `missing`       — not installed at all. The right-hand
 *                       label hints at the marketplace version
 *                       when we know one ("仓库提供 v1.5.0"),
 *                       or "未找到" when the marketplace has
 *                       no record of the id.
 *   - `unsatisfied`   — installed, but the local version
 *                       doesn't satisfy the declared range.
 *                       Red bang.
 *   - `cycle`         — appears in a detected cycle path. Red
 *                       lock-ish icon.
 *
 * Lifted into a small standalone component (instead of
 * inlined in the JSX) so the JSX inside `PluginMarketDetail`
 * stays focused on flow control — the resolver's bucket
 * structure drives the rendering, and putting that mapping
 * here keeps the dialog render path compact.
 */
function DependencyResolutionList({
  resolution,
}: {
  resolution: DependencyResolution
}) {
  const { t } = useTranslation()
  const { root } = resolution
  // Build a quick lookup so we can decorate each declared
  // dep with its resolved status. Unsatisfied / missing /
  // cycle / satisfied each have distinct entries.
  const missingById = new Map(resolution.missing.map((m) => [m.id, m]))
  const unsatisfiedById = new Map(
    resolution.unsatisfied.map((u) => [u.id, u]),
  )
  const cycleIds = new Set<string>()
  for (const c of resolution.cycles) {
    for (const id of c.path) cycleIds.add(id)
  }

  return (
    <ul
      data-testid="plugin-deps-list"
      style={{
        listStyle: 'none',
        margin: 0,
        padding: 0,
        display: 'flex',
        flexDirection: 'column',
        gap: 4,
      }}
    >
      {root.dependencies.map((dep) => {
        const inCycle = cycleIds.has(dep.id)
        const unsatisfied = unsatisfiedById.get(dep.id)
        const missing = missingById.get(dep.id)
        const status = inCycle
          ? {
              cls: 'is-cycle',
              icon: <AlertCircle size={12} />,
              label: t('plugin.market.depsStatusCycle', {
                defaultValue: '循环依赖',
              }),
            }
          : unsatisfied
          ? {
              cls: 'is-unsatisfied',
              icon: <AlertCircle size={12} />,
              label:
                unsatisfied.kind === 'invalid-range'
                  ? t('plugin.market.depsStatusInvalidRange', {
                      defaultValue: '清单中的依赖范围无效',
                    })
                  : unsatisfied.kind === 'unparseable-version'
                  ? t('plugin.market.depsStatusUnparseable', {
                      defaultValue: '已安装版本无法解析',
                    })
                  : t('plugin.market.depsStatusUnsatisfied', {
                      defaultValue: `本地 v${unsatisfied.installed}，需要 ${unsatisfied.required}`,
                    }),
            }
          : missing
          ? {
              cls: 'is-missing',
              icon: <AlertCircle size={12} />,
              label: missing.available
                ? t('plugin.market.depsStatusMissingWithAvailable', {
                    defaultValue: `仓库提供 v${missing.available}`,
                  })
                : t('plugin.market.depsStatusMissingNoSource', {
                    defaultValue: '未找到来源',
                  }),
            }
          : {
              cls: 'is-ok',
              icon: <CheckCircle2 size={12} />,
              label: t('plugin.market.depsStatusSatisfied', {
                defaultValue: '已满足',
              }),
            }
        return (
          <li
            key={dep.id}
            data-testid="plugin-dep-row"
            data-status={status.cls}
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: 6,
              padding: '4px 8px',
              border: '1px solid var(--border, #e5e5e5)',
              borderRadius: 4,
              fontSize: 12,
              fontFamily: 'var(--font-mono, monospace)',
            }}
          >
            <span
              style={{
                display: 'inline-flex',
                alignItems: 'center',
                flexShrink: 0,
                color:
                  status.cls === 'is-ok'
                    ? 'var(--success, #16a34a)'
                    : 'var(--danger, #c0392b)',
              }}
            >
              {status.icon}
            </span>
            <span style={{ flex: 1, minWidth: 0 }}>{dep.id}</span>
            <span
              style={{
                fontSize: 11,
                color:
                  status.cls === 'is-ok'
                    ? 'var(--text-secondary)'
                    : 'var(--danger, #c0392b)',
                fontFamily: 'var(--font-system, system-ui)',
              }}
            >
              {status.label}
            </span>
          </li>
        )
      })}
    </ul>
  )
}
